### ISSUE TITLE
v0.1.5

### ISSUE THREAD

**Issue by jmborr** [mcvine/mantid2mcvine#24]
### Tasks to finish

- [ ]  Update version in _version.py
- [ ] Update git tag and push:
```bash
git tag -a vX.X.X -m 'comment'
git push --tags
```
- [ ]  In [conda recipe](https://github.com/mcvine/conda-recipes/tree/master/mantid2mcvine), update meta.yaml and build

**Comment by jmborr** [comment]
@yxqd I don't have repo permissions to do this but we need to have a new conda package to update the `mcvine` conda env's in the analysis clusters, or if a user wants to install `mcvine` via conda, make sure `mantid2mcvine v.1.0.5` is installed as a dependency.
Can you please either take care of this or give me permissions to create a new  tag?

**Comment by yxqd** [comment]
@jmborr I just sent you an invitation to https://github.com/orgs/mcvine/teams/mcvine-dev. Hope that will give you the permission. Please let me know if it does not work. Thanks!
